### ISSUE TITLE
Parallelization changes sometimes throw FlurlHttpException stating the collection was modified

### ISSUE THREAD

**Issue by nlowe** [HylandSoftware/Harbor.Tagd#11]
After merging #10 we got an exception this morning while tag processing. This didn't happen while testing, I'll look into it.

```csharp
Flurl.Http.FlurlHttpException: Call failed. Collection was modified; enumeration operation may not execute. GET https://hcr.io/api/repositories/***/***/tags ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at Flurl.Http.FlurlRequest.WriteRequestCookies(HttpRequestMessage request)
   at Flurl.Http.FlurlRequest.<SendAsync>d__19.MoveNext()
   --- End of inner exception stack trace ---
   at Flurl.Http.FlurlRequest.<HandleExceptionAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Flurl.Http.FlurlRequest.<SendAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Flurl.Http.FlurlRequest.<SendAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Flurl.Http.HttpResponseMessageExtensions.<ReceiveJson>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Harbor.Tagd.API.HarborClient.<GetTags>d__13.MoveNext() in /home/jenkins/workspace/tagd-deployment_master-JF7YPWJZTOOXFXCSSMKKW3M2EI6YOS6ORV23RH3WIKLWAALDS2CA/tagd/src/Harbor.Tagd/API/HarborClient.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Harbor.Tagd.TagEngine.<ProcessRepository>d__12.MoveNext() in /home/jenkins/workspace/tagd-deployment_master-JF7YPWJZTOOXFXCSSMKKW3M2EI6YOS6ORV23RH3WIKLWAALDS2CA/tagd/src/Harbor.Tagd/TagEngine.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Harbor.Tagd.TagEngine.<ProcessProject>d__11.MoveNext() in /home/jenkins/workspace/tagd-deployment_master-JF7YPWJZTOOXFXCSSMKKW3M2EI6YOS6ORV23RH3WIKLWAALDS2CA/tagd/src/Harbor.Tagd/TagEngine.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Harbor.Tagd.TagEngine.<Process>d__9.MoveNext() in /home/jenkins/workspace/tagd-deployment_master-JF7YPWJZTOOXFXCSSMKKW3M2EI6YOS6ORV23RH3WIKLWAALDS2CA/tagd/src/Harbor.Tagd/TagEngine.cs:line 80
```

**Comment by nlowe** [comment]
Well shit: tmenier/Flurl#318. We [may be able to work around it](https://github.com/tmenier/Flurl/issues/328#issuecomment-395997205). More digging required!

**Comment by nlowe** [comment]
This breaks even if I explicitly create a single client and enable cookies before sending any requests. I think the best thing to do here is to revert #10 and deal with the slowdowns until this becomes a part of Harbor Proper (goharbor/harbor#5420). I don't really want to rewrite the API stack between then for some small performance increases.

**Comment by tmenier** [comment]
I know this is old but there's a much better cookie experience coming in Flurl 3.0 if you're still interested:

https://github.com/tmenier/Flurl/issues/506
