### ISSUE TITLE
Unable to run tagd harbor v.1.8.1 with oidc.

### ISSUE THREAD

**Issue by Andreiaotto** [HylandSoftware/Harbor.Tagd#28]
Hi, I'm trying to use tagd on harbor v.1.8.1, auth OIDC with Azure AD  in kubernetes, using tagd:1.7.2. 

We already tried multiple things, but always the same issue, with or without https:
```
[11:13:10 WRN] Ignoring Certificate Errors
[11:13:10 INF] Loading rules using Harbor.Tagd.Rules.FilesystemRuleProvider
[11:13:10 WRN] Not running in report-only mode. Tags will be deleted
[11:13:10 INF] Connecting to https://mydomain.com as harboruser
[11:13:10 WRN] Tags will be deleted when matched!
[11:13:10 FTL] An Error was encountered while processing tags
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Harbor.Tagd.API.HarborClient.<Login>d__13.MoveNext() in /home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/API/HarborClient.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Harbor.Tagd.TagEngine.<Process>d__9.MoveNext() in /home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/TagEngine.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Harbor.Tagd.TagEngine.<Process>d__9.MoveNext() in /home/travis/build/HylandSoftware/Harbor.Tagd/src/HarborTagd/TagEngine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Harbor.Tagd.TagEngine.<Process>d__9.MoveNext() in /home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/TagEngine.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Harbor.Tagd.Program.<DoClean>d__3.MoveNext() in home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/Program.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Harbor.Tagd.Program.<Main>d__2.MoveNext() in /home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/Program.cs:line 98
```

On harbor core pod logs I see `403 |  match| POST     /c/login   r:/c/login`
 

I'm using the CLI secret from the UI -> user profile to connect from tagd, docker login works from my machine, but no success to run tagd.

Any idea?

Thank you!

**Comment by nlowe** [comment]
I don't have an OIDC setup to test with unfortunately. Are you able to log into the web UI with this cli secret? If not, then it won't work with Tagd. I don't know if CLI secrets / Robot accounts can interact with the API. If they can, I would gladly accept a pull request adding support for them.

**Comment by Andreiaotto** [comment]
Hi @nlowe if I try to log into web UI with the user + cli secret it redirects me to Azure AD login page to continue, so the answer is no.

It's also failing with the same log to the admin (local) user, which is not linked to oidc.

It should work, correct? I don't find any other log to debug the problem.

thank you

**Comment by nlowe** [comment]
If you can still log into the web interface with ODIC mode enabled then yes, tagd should work with that account. I haven't upgraded my instance to 1.8 yet so I'm not sure what the configuration is like.

**Comment by Andreiaotto** [comment]
It turns out to work only with the admin local user in harbor. For now, not supported with oidc users.
Me and my team will check if we can contribute to support users with oidc.
