### ISSUE TITLE
Command/Docker container always return exit code 0 even on failure

### ISSUE THREAD

**Issue by akathimi** [HylandSoftware/Harbor.Tagd#32]
To reproduce, just run the docker container with false info: 
``` 
 docker run -it --rm -v config.yml:/config.yml hylandsoftware/tagd \
    --config-file /config.yml \
    --endpoint ar.ss.com \
    --user aa \
    --password 123
[13:39:16 INF] Loading rules using Harbor.Tagd.Rules.FilesystemRuleProvider
[13:39:16 FTL] An Error was encountered while processing tags
System.UnauthorizedAccessException: Access to the path '/config.yml' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Harbor.Tagd.Rules.FilesystemRuleProvider.Load() in /home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/Rules/FilesystemRuleProvider.cs:line 33
   at Harbor.Tagd.TagEngine.LoadRules() in /home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/TagEngine.cs:line 114
   at Harbor.Tagd.TagEngine.<Process>d__9.MoveNext() in /home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/TagEngine.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Harbor.Tagd.Program.<DoClean>d__3.MoveNext() in /home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/Program.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Harbor.Tagd.Program.<Main>d__2.MoveNext() in /home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/Program.cs:line 98





echo $?
0
```
This is causing containers/k8s pods(jobs) to show a COMPLETED status instead of ERROR

**Comment by nlowe** [comment]
Huh. Interesting. I don't know how I haven't noticed this before. What version are you running? The docker run command you used makes it sound like you're running `:latest`, is that correct?

**Comment by akathimi** [comment]
yes the above is using latest docker images. and on k8s we have it on a cronjob.
here is the kubectl describe pod:
```
Containers:
  tagd:
    Container ID:  docker://800c3f9050b9876e62624c6a7e88f8c472571f3221e2ffbe3d8b87576d6bdba4
    Image:         hylandsoftware/tagd:1.0.26
    Image ID:      docker-pullable://hylandsoftware/tagd@sha256:0dc655685ca94108cbd7b30e85f464fcd8d198b86d95c38efde47c008625ca1e
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -c
      dotnet /Harbor.Tagd.dll --config-file config.yaml/config.yaml  --endpoint $endpoint --user admin --password $password --destructive
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 21 Nov 2019 02:00:02 +0200
      Finished:     Thu, 21 Nov 2019 02:00:10 +0200
    Ready:          False
    Restart Count:  0
```

and here is the pod's log:
```
[00:00:08 WRN] Tags will be deleted when matched!
[00:00:10 FTL] An Error was encountered while processing tags
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Harbor.Tagd.API.HarborClient.<Login>d__13.MoveNext() in /home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/API/HarborClient.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Harbor.Tagd.TagEngine.<Process>d__9.MoveNext() in /home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/TagEngine.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Harbor.Tagd.TagEngine.<Process>d__9.MoveNext() in /home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/TagEngine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Harbor.Tagd.TagEngine.<Process>d__9.MoveNext() in /home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/TagEngine.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Harbor.Tagd.Program.<DoClean>d__3.MoveNext() in /home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/Program.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Harbor.Tagd.Program.<Main>d__2.MoveNext() in /home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/Program.cs:line 96
```

You can see that the error message is different but the exit code is always 0.

hope this helps :)

**Comment by nlowe** [comment]
We have a similar cron job setup internally. Thanks for the report, I'll try to take a closer look later this afternoon.

**Comment by nlowe** [comment]
Nice find! This was totally my fault. I'm used to Fatal errors exiting for you with Logrus in Go, it appears Serilog doesn't do that. I have a PR up now to fix it, I'll try to get that merged this week but it may take a bit for approvals due to a holiday in the US. You can make your own image from 43e4086 if you need something sooner.

**Comment by nlowe** [comment]
@akathimi This is now live in `docker pull hylandsoftware/tagd:1.7.5`

**Comment by akathimi** [comment]
@nlowe thanks
